name: Deploy Resume

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install YAMLResume
        run: |
          npm install -g yamlresume

      # Create a clean, dedicated folder for the web assets
      - name: Build HTML Resume
        run: |
          mkdir public
          yamlresume build --no-pdf resume.yaml
          mv resume.html public/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      # Point the artifact upload ONLY to the clean public folder
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4